[package]
name = "tan"
description = "The Tan language"
version = "0.8.0"
license = "Apache-2.0"
repository = "https://github.com/tan-language/tan"
keywords = ["language", "functional", "lisp"]
authors = ["Georgios Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
tracing = "0.1"
rand = "0.8"
