[package]
name = "tan"
description = "The Tan language"
version = "0.3.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tanlang-org/tan"
keywords = ["language", "functional", "lisp", "jsonrpc", "api"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
