[package]
name = "tan"
description = "The Tan language"
version = "0.7.0"
license = "Apache-2.0"
repository = "https://github.com/tanlang-org/tan"
keywords = ["language", "functional", "lisp", "jsonrpc", "api"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
tracing = "0.1"
